//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szofttech_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konyv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konyv()
        {
            this.RendelesOssz = new HashSet<RendelesOssz>();
        }
    
        public int idKonyv { get; set; }
        public string Nev { get; set; }
        public string Iro { get; set; }
        public Nullable<int> Ar { get; set; }
        public string Keszlet { get; set; }
        public int RaktarFK { get; set; }
    
        public virtual Raktar Raktar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendelesOssz> RendelesOssz { get; set; }
    }
}
