//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szofttech_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profil()
        {
            this.Ugyfel = new HashSet<Ugyfel>();
        }
    
        public int idUgyfelesAdatok { get; set; }
        public string Nev { get; set; }
        public string Email_Cim { get; set; }
        public Nullable<System.DateTime> SzuletesiDatum { get; set; }
        public string SzallitasiCim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ugyfel> Ugyfel { get; set; }
    }
}
