//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szofttech_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendelesOssz
    {
        public int idKapcsolo { get; set; }
        public int Rendeles_FK { get; set; }
        public int Konyv_FK { get; set; }
    
        public virtual Konyv Konyv { get; set; }
        public virtual Rendeles Rendeles { get; set; }
    }
}
