//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szofttech_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugyfel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ugyfel()
        {
            this.Rendeles = new HashSet<Rendeles>();
        }
    
        public int idUgyfel { get; set; }
        public int JogosultsagFK { get; set; }
        public int UgyfelesAdatokFK { get; set; }
    
        public virtual Jogosultsag Jogosultsag { get; set; }
        public virtual Profil Profil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles> Rendeles { get; set; }
    }
}
